### ISSUE TITLE
How many passes for HiFi reads?

### ISSUE THREAD

**Issue by marcomeola** [PacificBiosciences/pbAA#1]
Thank you for the useful tool. I have a multi copy region (5 copies) in bacterial genomes amplified with targeted amplicon sequencing on a sMRT cell v3. I do have some reference sequences as guides, so that's ok.

I have mainly three questions 

1) How many passes would you recommend to get HiFi subreads?
2) Would you recommend to polish the consensus sequences again after pbaa? If yes, which polisher would you suggest, gcpp, racon or arrow?
3) what option should be selected for pbaa pipeline during the HiFi construction: --hifi-kinetics or --by-strand?

Thanks

**Comment by zeeev** [comment]
Hi @marcomeola,

Apologies for the very late reply. 

Generally speaking PBAA works best with HiFi reads that have at least 3-10 passes, with more being better.

No, I would not recommend polishing the PBAA consensus sequences. We find, in genome assembly, polishing can introduce errors. Essentially, PBAA already runs a consensus algorithm similar to racon. 

PBAA just requires a fastq file. You could run by-strand if you suspect heteroduplex PCR products. 

If you have any additional questions feel free to re-open the ticket.
