### ISSUE TITLE
pbaa clustering on amplicon pools

### ISSUE THREAD

**Issue by SonjaKersten** [PacificBiosciences/pbAA#3]
Dear pbaa developers,

I am currently pushing the limits of your much-needed clustering algorithm with amplicon pools (150 individuals per pool) in a diploid plant. Amplicon size: 13.2 kb, 5300 CCS Q30 reads per pool.
Parameter settings:

pbaa cluster \
       ref.fa \
       --min-read-qv 30 \
       --min-var-frequency 0.02 \
       --min-cluster-read-count 3 \
       --min-cluster-frequency 0.0005 \
       --fixed-cluster-count 300 \
       $outputTMP/$acc.$GENE.$Q.fofn \
       $outputTMP/$acc.$Q.$GENE

1.	I am getting passed clusters with rather lower uchime scores and diversity 0. I was wondering what exactly these uchime scores mean and if I can somehow improve the performance of clustering to reduce these chimera clusters?

2.	Based on separate data (also analysed with pbaa) we have for individual samples, we think the number of passed clusters we get (11 to 26 per population for a pool of 150 diploid individuals) is quite likely an underestimate. Therefore I reduced the min-var-frequency to 0.02 hoping this would provide more resolution, though I admit, I don’t know whether that was a correct thought. Nevertheless, it didn’t change the number of passed clusters. 
- Closer inspection of the "pbaa bampaint" output in IGV revealed that the CCS-reads carrying the SNP mutation we are interested in is classified as the same cluster as the WT counterpart (one SNP away!).  
- Would you recommend a combination of parameter settings to improve this further from the get-go?
- What if I run a second iteration of pbaa on the raw-CCS-reads belonging to high frequency clusters, but this time with default  setting (incl. --fixed-cluster-count). Would you foresee a problem with that?  

Thanks in advance,

Sonja

**Comment by zeeev** [comment]
Hi @SonjaKersten,

Thank you for reaching out and sharing your experience. As we mention in the README, we haven't had the opportunity to test the software on pooled data. Would you be willing to share some of your data? 

1. The Chimera score uses the UCHIME algorithm which is detailed here: ([link](https://www.drive5.com/usearch/manual/uchime_algo.html)) 

2. It sounds like PBAA is failing to identify a few variants, collapsing clusters. 

3. It's possible that some clusters are being marked as failed only because they are low frequency. PBAA can under-estimate cluster frequency, and fall below the threshold. How many of the expected haplotypes are falling into the `failed` bin.

I'd be happy to test a few settings on these data if you can share it. If not, I'll think about which parameters might need to be changed for this experiment. 

Best wishes,

Zev

**Comment by SonjaKersten** [comment]
![image](https://user-images.githubusercontent.com/76657951/108495657-5b326180-72a9-11eb-9314-9c144da9d120.png)

Since I could not upload the fastq files here due to their size, I sent them to your email address.

**Comment by zeeev** [comment]
Thanks! I'll take a look today.

**Comment by SonjaKersten** [comment]
Dear Zev,

My apologies, I also sent you the guide sequence now.
In the meantime I ran a second pbaa clustering iteration in one of the problematic clusters and again it failed to separate it. However, I noticed that my two problematic alleles were CCT and TTC, so I disabled homopolymer compression (--no-hpc). Thus, I resolved it correctly. The cluster frequency of the second cluster was then 10%, but it was marked as a duplicated failed cluster. What sensitivity parameter do I need to change to mark it as a real cluster.
What is your experience with disabling hpc correction. Does it lead to significantly more errors?

Best Sonja

**Comment by zeeev** [comment]
Hi @SonjaKersten,

If you're using the no-hpc flag you may encounter additional clusters that only differ by homopolymer sequencing error. Subjectively speaking, for a diploid, I see a 0-3 extra clusters per sample, but they tend to be low frequency, and tend to end up in the `failed file`.  

I've opened an internal bug report regaurding `no-hpc` duplicate marking. During duplicate marking `no-hpc` flag is ignored, so the consensus sequences are compressed, and HP differences are ignored. I'll fix this.

The pass/fail determination is a series of heuristics trained on HLA data. In your case, I'd concatenate the pass/fail into one file, map them to the reference/guide(s), and view both the clusters, and the painted reads. It should help establish better cutoffs (pass/fail) for your pools. 

I'm looking at your data, but it might take me a few days before I get back to you.

Best wishes,

**Comment by zeeev** [comment]
Hi @SonjaKersten,

Just wanted to let you know I've run one of the samples. Yes, there's a good number of sequences that are marked as duplicated. I'm trying out removing homolpolymer compression during duplicate detection.

**Comment by SonjaKersten** [comment]
Dear Zev,

Thanks for running our samples. 
I have previously tested a few runtimes with different numbers of clusters. I ran it with 10 cores x 10 Gb of memory on a high computing cluster. Parameter --fixed-cluster-count:

150: Run time: 2 hours
200: 3 hours
300: 7 hours
400: 15-22 hours (here, I changed number of cores to 20 cores x 10 Gb memory).

Best Sonja

**Comment by SonjaKersten** [comment]
Dear Zev,

Do you have news on the bug fix of the duplicated clusters you mentioned, so that I could give it a try to it?

Since we have such a high number of expected clusters and you experienced "0-3 additional clusters per sample" when enabling the --no-hpc flag, we tried two clustering iterations:

A first round of clustering with the parameters and high expected cluster counts as described before (but without --no-hpc), then we recovered the reads that made it into each cluster and did a second clustering iteration, this time with --min-read-qv 30 --min-var-frequency 0.02 --min-cluster-read-count 10 --min-cluster-frequency 0.001 --fixed-cluster-count 10 --no-hpc --no-indel. This actually gives us reasonable clusters and our known multiallelic sites are split correctly.  We wonder whether a 2 iterations approach for complex datasets like large pools would be valid and conservative? Do you have any objections or thoughts about this two-step procedure?

Best and thanks,

Sonja

**Comment by zeeev** [comment]
Hi @SonjaKersten,

PBAA has been updated, extending `--no-hpc` into the mark duplicates function. Please reopen if need be.
